// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  $(document).ready(function() {
    var Grid, Inventory, Machine, PlayingGrid, Slot, grid, inventory, uid;
    uid = (function() {
      var id;
      id = 0;
      return function() {
        return id++;
      };
    })();
    Grid = (function() {
      function Grid(width1, height1, element1) {
        var cell, j, k, ref, ref1, row, x, y;
        this.width = width1;
        this.height = height1;
        this.element = element1;
        this.slots = (function() {
          var j, ref, results;
          results = [];
          for (j = 1, ref = this.width * this.height; 1 <= ref ? j <= ref : j >= ref; 1 <= ref ? j++ : j--) {
            results.push(null);
          }
          return results;
        }).call(this);
        for (y = j = 0, ref = this.height; 0 <= ref ? j <= ref : j >= ref; y = 0 <= ref ? ++j : --j) {
          row = $('<div/>', {
            "class": 'row'
          });
          for (x = k = 0, ref1 = this.width; 0 <= ref1 ? k <= ref1 : k >= ref1; x = 0 <= ref1 ? ++k : --k) {
            cell = $('<div/>', {
              "class": 'cell'
            });
            if (x < this.width && y < this.height) {
              this.slots[this.toSlotIndex(x, y)] = new Slot(cell);
            }
            row.append(cell);
          }
          this.element.append(row);
        }
      }

      Grid.prototype.getSlot = function(x, y) {
        return this.slots[this.toSlotIndex(x, y)];
      };

      Grid.prototype.toSlotIndex = function(x, y) {
        return x + y * this.width;
      };

      return Grid;

    })();
    PlayingGrid = (function(superClass) {
      extend(PlayingGrid, superClass);

      function PlayingGrid(width, height, element) {
        var cell, dir, j, k, l, len, len1, len2, ref, ref1, ref2, row, x, y;
        PlayingGrid.__super__.constructor.call(this, width, height, element);
        this.edges = (function() {
          var j, ref, results;
          results = [];
          for (j = 1, ref = (this.width + 1) * (this.height + 1) * 2; 1 <= ref ? j <= ref : j >= ref; 1 <= ref ? j++ : j--) {
            results.push(null);
          }
          return results;
        }).call(this);
        ref = this.element.children('.row');
        for (y = j = 0, len = ref.length; j < len; y = ++j) {
          row = ref[y];
          ref1 = $(row).children('.cell');
          for (x = k = 0, len1 = ref1.length; k < len1; x = ++k) {
            cell = ref1[x];
            ref2 = ['left', 'up'];
            for (l = 0, len2 = ref2.length; l < len2; l++) {
              dir = ref2[l];
              $(cell).append($('<div/>', {
                "class": 'number ' + dir,
                id: 'number-' + this.toEdgeIndex(x, y, dir)
              }));
            }
          }
        }
      }

      PlayingGrid.prototype.getEdge = function(x, y, dir) {
        return this.edges[this.toEdgeIndex(x, y, dir)];
      };

      PlayingGrid.prototype.setEdge = function(x, y, dir, value) {
        var edge_index;
        edge_index = this.toEdgeIndex(x, y, dir);
        this.element.find('#number-' + edge_index).text(value != null ? value : '');
        return this.edges[edge_index] = value;
      };

      PlayingGrid.prototype.toEdgeIndex = function(x, y, dir) {
        if (dir === 'up') {
          return (x + y * (this.width + 1)) * 2 + 1;
        } else if (dir === 'left') {
          return (x + y * (this.width + 1)) * 2;
        } else if (dir === 'right') {
          return this.toEdgeIndex(x + 1, y, 'left');
        } else if (dir === 'down') {
          return this.toEdgeIndex(x, y + 1, 'up');
        }
      };

      PlayingGrid.prototype.update = function() {
        var dir, i, j, jammed, k, l, len, m, machine, ref, ref1, ref2, ref3, results, supplied, value, x, y;
        for (x = j = 0, ref = this.width; 0 <= ref ? j < ref : j > ref; x = 0 <= ref ? ++j : --j) {
          for (y = k = 0, ref1 = this.height; 0 <= ref1 ? k < ref1 : k > ref1; y = 0 <= ref1 ? ++k : --k) {
            machine = this.getSlot(x, y).machine;
            if (machine != null) {
              if (machine.contents == null) {
                supplied = true;
                ref2 = machine.inputs;
                for (l = 0, len = ref2.length; l < len; l++) {
                  value = ref2[l];
                  if (this.getEdge(x, y, value) == null) {
                    supplied = false;
                  }
                }
                if (supplied) {
                  machine.contents = (function() {
                    var len1, m, ref3, results;
                    ref3 = machine.inputs;
                    results = [];
                    for (m = 0, len1 = ref3.length; m < len1; m++) {
                      dir = ref3[m];
                      value = this.getEdge(x, y, dir);
                      this.setEdge(x, y, dir, null);
                      results.push(value);
                    }
                    return results;
                  }).call(this);
                  machine.contents = machine["function"](machine.contents);
                }
              }
            }
          }
        }
        results = [];
        for (x = m = 0, ref3 = this.width; 0 <= ref3 ? m < ref3 : m > ref3; x = 0 <= ref3 ? ++m : --m) {
          results.push((function() {
            var len1, len2, n, o, p, ref4, ref5, ref6, results1;
            results1 = [];
            for (y = n = 0, ref4 = this.height; 0 <= ref4 ? n < ref4 : n > ref4; y = 0 <= ref4 ? ++n : --n) {
              machine = this.getSlot(x, y).machine;
              if (machine != null) {
                if (machine.contents != null) {
                  jammed = false;
                  ref5 = machine.outputs;
                  for (o = 0, len1 = ref5.length; o < len1; o++) {
                    value = ref5[o];
                    if (this.getEdge(x, y, value) !== null) {
                      jammed = true;
                    }
                  }
                  if (!jammed) {
                    ref6 = machine.contents;
                    for (i = p = 0, len2 = ref6.length; p < len2; i = ++p) {
                      value = ref6[i];
                      this.setEdge(x, y, machine.outputs[i], value);
                    }
                    results1.push(machine.contents = null);
                  } else {
                    results1.push(void 0);
                  }
                } else {
                  results1.push(void 0);
                }
              } else {
                results1.push(void 0);
              }
            }
            return results1;
          }).call(this));
        }
        return results;
      };

      return PlayingGrid;

    })(Grid);
    Inventory = (function(superClass) {
      extend(Inventory, superClass);

      function Inventory(width, height, element) {
        Inventory.__super__.constructor.call(this, width, height, element);
      }

      Inventory.prototype.addMachine = function(machine) {
        var freeSlots, slot;
        freeSlots = (function() {
          var j, len, ref, results;
          ref = this.slots;
          results = [];
          for (j = 0, len = ref.length; j < len; j++) {
            slot = ref[j];
            if (slot.machine == null) {
              results.push(slot);
            }
          }
          return results;
        }).call(this);
        if (freeSlots.length > 0) {
          return freeSlots[0].moveMachine(machine);
        }
      };

      return Inventory;

    })(Grid);
    Slot = (function() {
      function Slot(parent_element) {
        this.machine = null;
        parent_element.append(this._makeHtml());
      }

      Slot.prototype._makeHtml = function() {
        this.element = $('<div/>', {
          "class": 'slot',
          ondrop: 'window.dropSlot(event)',
          ondragover: 'event.preventDefault()'
        });
        return this.element.data('class', this);
      };

      Slot.prototype.moveMachine = function(machine) {
        var machineHtml, oldSlot;
        machineHtml = machine.getHtml();
        oldSlot = machineHtml.parent().data('class');
        if (oldSlot != null) {
          oldSlot.machine = null;
        }
        if (this.machine == null) {
          this.machine = machine;
          return this.element.append(machineHtml);
        }
      };

      return Slot;

    })();
    Machine = (function() {
      function Machine(inputs, outputs, _function) {
        this.inputs = inputs != null ? inputs : [];
        this.outputs = outputs != null ? outputs : [];
        this["function"] = _function != null ? _function : (function(i) {
          return i;
        });
        this.contents = null;
        this.id = uid();
      }

      Machine.prototype.getHtml = function() {
        var dir, j, k, len, len1, list, name, ref, ref1, ref2;
        if (this.element == null) {
          this.element = $('<div/>', {
            "class": 'machine',
            id: 'machine-' + this.id,
            draggable: true,
            ondragstart: 'window.dragMachine(event)'
          });
          ref = [[this.inputs, 'input'], [this.outputs, 'output']];
          for (j = 0, len = ref.length; j < len; j++) {
            ref1 = ref[j], list = ref1[0], name = ref1[1];
            ref2 = ['up', 'down', 'left', 'right'];
            for (k = 0, len1 = ref2.length; k < len1; k++) {
              dir = ref2[k];
              if (indexOf.call(list, dir) >= 0) {
                this.element.append($('<div/>', {
                  "class": 'port ' + name + ' ' + dir
                }));
              }
            }
          }
          this.element.data('class', this);
        }
        return this.element;
      };

      return Machine;

    })();
    window.dragMachine = function(e) {
      return e.dataTransfer.setData('text', e.target.id);
    };
    window.dropSlot = function(e) {
      var machine, machineId, slot;
      e.preventDefault();
      machineId = e.dataTransfer.getData('text');
      machine = $('#' + machineId).data('class');
      slot = $(e.target).data('class');
      if (slot instanceof Slot) {
        return slot.moveMachine(machine);
      }
    };
    grid = new PlayingGrid(5, 5, $('#grid'));
    inventory = new Inventory(2, 6, $('#inventory'));
    inventory.addMachine(new Machine([], ['down'], function() {
      if (this.t != null) {
        return this.t = null;
      } else {
        return this.t = (function() {
          var j, ref, results;
          results = [];
          for (j = 1, ref = this.outputs.length; 1 <= ref ? j <= ref : j >= ref; 1 <= ref ? j++ : j--) {
            results.push(Math.floor(Math.random() * 10));
          }
          return results;
        }).call(this);
      }
    }));
    inventory.addMachine(new Machine(['up'], ['down', 'right'], function(i) {
      return i.concat(i);
    }));
    inventory.addMachine(new Machine(['left'], ['down'], function(i) {
      return i.map(function(a) {
        return a * 2;
      });
    }));
    inventory.addMachine(new Machine(['up'], ['right']));
    inventory.addMachine(new Machine(['up', 'left'], ['right'], function(i) {
      return [
        i.reduce(function(a, b) {
          return a + b;
        })
      ];
    }));
    inventory.addMachine(new Machine(['left']));
    return setInterval(function() {
      return grid.update();
    }, 1000);
  });

}).call(this);

//# sourceMappingURL=index.js.map
